import type { Circle } from "@/lib/types";

export const SEED_CIRCLES: Circle[] = [
  {
    id: "c1",
    name: "SF AI Builders",
    description: "Engineers, researchers, and founders building with AI in the Bay. Weekly discussions on tools, papers, demos, and the state of the field.",
    coverImage: "https://picsum.photos/seed/sfaibuilders/800/400",
    emoji: "🤖",
    category: "Technology",
    memberCount: 142,
    members: [
      { userId: "u1", role: "admin", joinedAt: "2026-01-10T09:00:00Z" },
      { userId: "u5", role: "member", joinedAt: "2026-01-25T09:00:00Z" },
      { userId: "u9", role: "member", joinedAt: "2026-02-10T09:00:00Z" },
      { userId: "u11", role: "moderator", joinedAt: "2026-02-08T09:00:00Z" },
      { userId: "u13", role: "member", joinedAt: "2026-02-12T09:00:00Z" },
      { userId: "u16", role: "member", joinedAt: "2026-01-20T09:00:00Z" },
      { userId: "u21", role: "member", joinedAt: "2026-02-22T09:00:00Z" },
      { userId: "u24", role: "member", joinedAt: "2026-03-08T09:00:00Z" },
      { userId: "u29", role: "member", joinedAt: "2026-03-20T09:00:00Z" },
    ],
    posts: [
      {
        id: "p1",
        circleId: "c1",
        authorId: "u1",
        authorName: "Maya Chen",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4",
        title: "What's everyone's current stack for building AI agents?",
        body: "Been exploring LangGraph vs building my own orchestration. Curious what people are actually using in production. Are you going full framework or rolling custom?",
        category: "Discussion",
        upvotes: 34,
        replies: [
          {
            id: "r1",
            authorId: "u13",
            authorName: "Ravi Menon",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4",
            content: "At Anthropic we use a mix of custom orchestration and some internal tooling. For side projects I've been loving the Vercel AI SDK — it handles streaming beautifully.",
            upvotes: 18,
            createdAt: "2026-06-10T11:00:00Z",
          },
          {
            id: "r2",
            authorId: "u9",
            authorName: "Sam Park",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4",
            content: "For the CityGen project I just went raw with async Python + Anthropic SDK. The frameworks add too much magic. You lose control fast.",
            upvotes: 12,
            createdAt: "2026-06-10T13:00:00Z",
          },
        ],
        createdAt: "2026-06-10T09:00:00Z",
        isPinned: false,
      },
      {
        id: "p2",
        circleId: "c1",
        authorId: "u11",
        authorName: "Noah Goldberg",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=noah&backgroundColor=ffd5dc",
        title: "AI in mental health apps — responsible design principles",
        body: "Building Anchor and constantly wrestling with where AI can genuinely help vs. where it creates risk. Would love to workshop this with others who are building in sensitive domains.",
        category: "Discussion",
        upvotes: 27,
        replies: [
          {
            id: "r3",
            authorId: "u1",
            authorName: "Maya Chen",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4",
            content: "This is so important. The Turing trap (making AI seem more capable than it is) is especially dangerous in mental health. Happy to connect.",
            upvotes: 15,
            createdAt: "2026-06-11T10:00:00Z",
          },
        ],
        createdAt: "2026-06-11T08:00:00Z",
        isPinned: true,
      },
      {
        id: "p3",
        circleId: "c1",
        authorId: "u21",
        authorName: "Brandon Osei",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=brandon&backgroundColor=b6e3f4",
        title: "Resource: Best papers to understand Claude's capabilities in 2026",
        body: "Compiled a reading list for founders and engineers who want to understand the frontier model landscape without getting lost in the weeds. Link in comments.",
        category: "Resource",
        upvotes: 51,
        replies: [
          {
            id: "r4",
            authorId: "u13",
            authorName: "Ravi Menon",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4",
            content: "Adding: the Constitutional AI paper is underrated as a product design document, not just alignment research.",
            upvotes: 22,
            createdAt: "2026-06-09T15:00:00Z",
          },
        ],
        createdAt: "2026-06-09T12:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "SoMa",
    city: "San Francisco",
    createdAt: "2026-01-10T09:00:00Z",
    isPublic: true,
    tags: ["AI", "Startups", "Engineering", "Research"],
  },
  {
    id: "c2",
    name: "Bay Area Designers",
    description: "Product designers, brand designers, UX researchers, and visual artists across the Bay. Portfolio shares, feedback sessions, and design discourse.",
    coverImage: "https://picsum.photos/seed/baydesigners/800/400",
    emoji: "✏️",
    category: "Design",
    memberCount: 89,
    members: [
      { userId: "u2", role: "admin", joinedAt: "2026-01-18T09:00:00Z" },
      { userId: "u15", role: "member", joinedAt: "2026-02-20T09:00:00Z" },
      { userId: "u20", role: "moderator", joinedAt: "2026-02-18T09:00:00Z" },
      { userId: "u29", role: "member", joinedAt: "2026-03-20T09:00:00Z" },
    ],
    posts: [
      {
        id: "p4",
        circleId: "c2",
        authorId: "u2",
        authorName: "Jordan Pierce",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=d1f0c2",
        title: "Critique my portfolio refresh — brutally honest feedback welcome",
        body: "Finally rebuilt my portfolio from scratch. Going for a quieter, slower feel — less grid, more story. Link in comments. I want the truth, not validation.",
        category: "Question",
        upvotes: 19,
        replies: [
          {
            id: "r5",
            authorId: "u15",
            authorName: "Marcus Webb",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=ffd5dc",
            content: "The type hierarchy on the case study pages is doing too much. One scale, one weight. Let the work breathe. The motion is great though — don't touch that.",
            upvotes: 11,
            createdAt: "2026-06-11T16:00:00Z",
          },
        ],
        createdAt: "2026-06-11T14:00:00Z",
        isPinned: false,
      },
      {
        id: "p5",
        circleId: "c2",
        authorId: "u20",
        authorName: "Yuki Tanaka",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=yuki&backgroundColor=c0aede",
        title: "Service design vs. UX design — where does the line actually sit?",
        body: "Had an argument with a PM yesterday about whether journey mapping is 'UX' or 'strategy'. I have opinions. What does the room think?",
        category: "Discussion",
        upvotes: 23,
        replies: [],
        createdAt: "2026-06-10T10:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    createdAt: "2026-01-18T09:00:00Z",
    isPublic: true,
    tags: ["Design", "UX", "Product", "Brand"],
  },
  {
    id: "c3",
    name: "Oakland Creatives",
    description: "Artists, musicians, writers, and makers in Oakland. Share your work, find collaborators, and build the city's creative scene together.",
    coverImage: "https://picsum.photos/seed/oaklandcreatives/800/400",
    emoji: "🎨",
    category: "Arts & Culture",
    memberCount: 203,
    members: [
      { userId: "u4", role: "admin", joinedAt: "2026-02-01T09:00:00Z" },
      { userId: "u10", role: "moderator", joinedAt: "2026-01-28T09:00:00Z" },
      { userId: "u16", role: "member", joinedAt: "2026-01-20T09:00:00Z" },
      { userId: "u21", role: "member", joinedAt: "2026-02-22T09:00:00Z" },
      { userId: "u23", role: "member", joinedAt: "2026-03-10T09:00:00Z" },
      { userId: "u28", role: "member", joinedAt: "2026-02-28T09:00:00Z" },
    ],
    posts: [
      {
        id: "p6",
        circleId: "c3",
        authorId: "u10",
        authorName: "Destiny Flores",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=destiny&backgroundColor=d1f0c2",
        title: "Looking for musicians to collaborate on the Fruitvale mural opening",
        body: "The mural goes up June 30th. I want live music at the opening — ideally something that reflects the neighborhood. Oakland artists only please. DM or reply here.",
        category: "Discussion",
        upvotes: 38,
        replies: [
          {
            id: "r6",
            authorId: "u4",
            authorName: "Kai Nakamura",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
            content: "I'm in. I'll bring the full kit. What vibe are you going for — ambient, jazz, something with more energy?",
            upvotes: 14,
            createdAt: "2026-06-09T11:00:00Z",
          },
          {
            id: "r7",
            authorId: "u23",
            authorName: "Jaylen Brooks",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jaylen&backgroundColor=ffd5dc",
            content: "Would love to perform at this. My EP just came out — very much Oakland summer vibes.",
            upvotes: 9,
            createdAt: "2026-06-09T14:00:00Z",
          },
        ],
        createdAt: "2026-06-09T09:00:00Z",
        isPinned: true,
      },
      {
        id: "p7",
        circleId: "c3",
        authorId: "u28",
        authorName: "Naomi Hecht",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=naomi&backgroundColor=c0aede",
        title: "Textile meets technology — anyone working at this intersection?",
        body: "I've been weaving circuits into fabric. It's weird and I love it. Are there any other Oakland makers combining traditional craft with electronics or code?",
        category: "Question",
        upvotes: 21,
        replies: [],
        createdAt: "2026-06-10T15:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Uptown",
    city: "Oakland",
    createdAt: "2026-02-01T09:00:00Z",
    isPublic: true,
    tags: ["Art", "Music", "Photography", "Collaboration"],
  },
  {
    id: "c4",
    name: "SF Photo Club",
    description: "Photographers of every level sharing work, going on photo walks, and learning from each other. All gear, all genres, all skill levels.",
    coverImage: "https://picsum.photos/seed/sfphotoclub/800/400",
    emoji: "📷",
    category: "Photography",
    memberCount: 117,
    members: [
      { userId: "u6", role: "admin", joinedAt: "2026-02-05T09:00:00Z" },
      { userId: "u2", role: "member", joinedAt: "2026-01-18T09:00:00Z" },
      { userId: "u16", role: "member", joinedAt: "2026-01-20T09:00:00Z" },
      { userId: "u25", role: "member", joinedAt: "2026-03-15T09:00:00Z" },
    ],
    posts: [
      {
        id: "p8",
        circleId: "c4",
        authorId: "u6",
        authorName: "Leo Fontaine",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2",
        title: "Photo walk this Saturday — meet at Dogpatch 9am",
        body: "We'll walk from Dogpatch through Potrero and SoMa. Golden hour hits around 6pm but morning light in the warehouses is perfect. Bring whatever camera you have.",
        category: "Event",
        upvotes: 29,
        replies: [
          {
            id: "r8",
            authorId: "u25",
            authorName: "Andre Santos",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andre&backgroundColor=b6e3f4",
            content: "I'm in. I'll bring the Leica. Anyone shooting film?",
            upvotes: 7,
            createdAt: "2026-06-11T12:00:00Z",
          },
        ],
        createdAt: "2026-06-11T09:00:00Z",
        isPinned: false,
      },
      {
        id: "p9",
        circleId: "c4",
        authorId: "u25",
        authorName: "Andre Santos",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andre&backgroundColor=b6e3f4",
        title: "Zine printing resources in SF — who do you use?",
        body: "About to print 200 copies of my first zine. Used Red Ink before but looking for alternatives. Any recommendations for short-run photobooks or zines?",
        category: "Question",
        upvotes: 16,
        replies: [],
        createdAt: "2026-06-10T16:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Dogpatch",
    city: "San Francisco",
    createdAt: "2026-02-05T09:00:00Z",
    isPublic: true,
    tags: ["Photography", "Photo Walk", "Documentary", "Film"],
  },
  {
    id: "c5",
    name: "Mission Neighborhood",
    description: "For residents, workers, and people who love the Mission District. Local news, events, mutual aid, and community organizing.",
    coverImage: "https://picsum.photos/seed/missionneighborhood/800/400",
    emoji: "🌮",
    category: "Neighborhood",
    memberCount: 312,
    members: [
      { userId: "u7", role: "admin", joinedAt: "2026-01-22T09:00:00Z" },
      { userId: "u3", role: "member", joinedAt: "2026-01-20T09:00:00Z" },
      { userId: "u10", role: "member", joinedAt: "2026-01-28T09:00:00Z" },
      { userId: "u14", role: "member", joinedAt: "2026-02-15T09:00:00Z" },
      { userId: "u17", role: "member", joinedAt: "2026-02-25T09:00:00Z" },
      { userId: "u20", role: "member", joinedAt: "2026-02-18T09:00:00Z" },
      { userId: "u30", role: "moderator", joinedAt: "2026-01-08T09:00:00Z" },
    ],
    posts: [
      {
        id: "p10",
        circleId: "c5",
        authorId: "u7",
        authorName: "Tomás Rivera",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=ffd5dc",
        title: "24th Street mural restoration — need volunteers this weekend",
        body: "The old Balmy Alley mural is getting restored Saturday. Bring paint clothes and a good attitude. The organizer is Destiny Flores — she's leading it. Coffee provided.",
        category: "Event",
        upvotes: 44,
        replies: [
          {
            id: "r9",
            authorId: "u3",
            authorName: "Aisha Okonkwo",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede",
            content: "I'll be there with 4 people from the food hub. What time does it start?",
            upvotes: 8,
            createdAt: "2026-06-10T10:00:00Z",
          },
        ],
        createdAt: "2026-06-10T08:00:00Z",
        isPinned: true,
      },
      {
        id: "p11",
        circleId: "c5",
        authorId: "u30",
        authorName: "Rosa Delgado",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rosa&backgroundColor=d1f0c2",
        title: "Community garden plot lottery — applications open",
        body: "MOECD is doing the annual garden plot lottery on Valencia. 12 new plots available this year. Application deadline is June 30. Link in comments.",
        category: "Resource",
        upvotes: 35,
        replies: [],
        createdAt: "2026-06-08T09:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Mission",
    city: "San Francisco",
    createdAt: "2026-01-08T09:00:00Z",
    isPublic: true,
    tags: ["Neighborhood", "Community", "Mutual Aid", "Local Events"],
  },
  {
    id: "c6",
    name: "Bay Area Social Impact",
    description: "Nonprofit leaders, social entrepreneurs, activists, and anyone building a better Bay Area. Strategy, funding, and coalition building.",
    coverImage: "https://picsum.photos/seed/socialimpact/800/400",
    emoji: "🤝",
    category: "Social Impact",
    memberCount: 178,
    members: [
      { userId: "u3", role: "admin", joinedAt: "2026-01-20T09:00:00Z" },
      { userId: "u5", role: "member", joinedAt: "2026-01-25T09:00:00Z" },
      { userId: "u7", role: "member", joinedAt: "2026-01-22T09:00:00Z" },
      { userId: "u12", role: "moderator", joinedAt: "2026-01-30T09:00:00Z" },
      { userId: "u19", role: "member", joinedAt: "2026-02-03T09:00:00Z" },
      { userId: "u30", role: "member", joinedAt: "2026-01-08T09:00:00Z" },
    ],
    posts: [
      {
        id: "p12",
        circleId: "c6",
        authorId: "u3",
        authorName: "Aisha Okonkwo",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede",
        title: "Anyone have a connection to the SF Dept of Public Health for a partnership ask?",
        body: "Working on a new initiative to get the food hub formally recognized as a community health resource. Need a warm intro to someone in SFDPH. Any connections appreciated.",
        category: "Question",
        upvotes: 14,
        replies: [
          {
            id: "r10",
            authorId: "u19",
            authorName: "Marcus Obi",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcusobi&backgroundColor=ffd5dc",
            content: "I have a contact at DPH from my public defender days. DMing you now.",
            upvotes: 10,
            createdAt: "2026-06-11T14:00:00Z",
          },
        ],
        createdAt: "2026-06-11T12:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "SoMa",
    city: "San Francisco",
    createdAt: "2026-01-20T09:00:00Z",
    isPublic: true,
    tags: ["Nonprofit", "Social Enterprise", "Community", "Advocacy"],
  },
  {
    id: "c7",
    name: "Bay Area Writers & Thinkers",
    description: "A circle for writers, journalists, essayists, podcasters, and people who think too much. Share work, find readers, workshop ideas.",
    coverImage: "https://picsum.photos/seed/writersthinkers/800/400",
    emoji: "📚",
    category: "Writing",
    memberCount: 94,
    members: [
      { userId: "u8", role: "admin", joinedAt: "2026-01-15T09:00:00Z" },
      { userId: "u11", role: "member", joinedAt: "2026-02-08T09:00:00Z" },
      { userId: "u18", role: "member", joinedAt: "2026-03-01T09:00:00Z" },
      { userId: "u19", role: "member", joinedAt: "2026-02-03T09:00:00Z" },
      { userId: "u22", role: "member", joinedAt: "2026-03-05T09:00:00Z" },
      { userId: "u24", role: "member", joinedAt: "2026-03-08T09:00:00Z" },
      { userId: "u26", role: "member", joinedAt: "2026-01-25T09:00:00Z" },
    ],
    posts: [
      {
        id: "p13",
        circleId: "c7",
        authorId: "u8",
        authorName: "Zara Washington",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zara&backgroundColor=c0aede",
        title: "Looking for workshop readers — draft essay on Oakland gentrification",
        body: "I have a 4,000-word draft and I need 3 people to read it before I submit to the Chronicle. Looking for people who know the city AND can give structural notes, not just copyediting.",
        category: "Question",
        upvotes: 22,
        replies: [
          {
            id: "r11",
            authorId: "u22",
            authorName: "Mei Lin",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=meilin&backgroundColor=d1f0c2",
            content: "I'll read it. I've been thinking about the same questions from a speculative fiction angle — might give you an unusual perspective.",
            upvotes: 9,
            createdAt: "2026-06-10T12:00:00Z",
          },
        ],
        createdAt: "2026-06-10T09:00:00Z",
        isPinned: false,
      },
      {
        id: "p14",
        circleId: "c7",
        authorId: "u26",
        authorName: "Kezia Atieno",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2",
        title: "Research request: anyone data-rich on mixed-use zoning outcomes?",
        body: "Dissertation chapter on transit-oriented development and community cohesion. Need 2019-2024 data for Oakland mixed-use corridors. Anyone with access to city planning datasets?",
        category: "Resource",
        upvotes: 11,
        replies: [],
        createdAt: "2026-06-09T15:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Rockridge",
    city: "Oakland",
    createdAt: "2026-01-15T09:00:00Z",
    isPublic: true,
    tags: ["Writing", "Journalism", "Essays", "Books"],
  },
  {
    id: "c8",
    name: "Creative Collabs",
    description: "The Bay's cross-discipline creative collaboration circle. Find a co-creator, workshop a project, or just be inspired.",
    coverImage: "https://picsum.photos/seed/creativecollabs/800/400",
    emoji: "🌀",
    category: "Collaboration",
    memberCount: 156,
    members: [
      { userId: "u4", role: "admin", joinedAt: "2026-02-01T09:00:00Z" },
      { userId: "u6", role: "member", joinedAt: "2026-02-05T09:00:00Z" },
      { userId: "u15", role: "member", joinedAt: "2026-02-20T09:00:00Z" },
      { userId: "u23", role: "member", joinedAt: "2026-03-10T09:00:00Z" },
      { userId: "u25", role: "member", joinedAt: "2026-03-15T09:00:00Z" },
      { userId: "u28", role: "member", joinedAt: "2026-02-28T09:00:00Z" },
    ],
    posts: [
      {
        id: "p15",
        circleId: "c8",
        authorId: "u4",
        authorName: "Kai Nakamura",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
        title: "Seeking a visual artist for a music x art installation",
        body: "I'm doing a live set at Oakland Museum next month and I want a visual artist to create a real-time projection that responds to the music. Budget is small but the exposure is good. Serious inquiries only.",
        category: "Discussion",
        upvotes: 31,
        replies: [
          {
            id: "r12",
            authorId: "u16",
            authorName: "Aaliyah Turner",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aaliyah&backgroundColor=c0aede",
            content: "My thesis project literally does this — generative visuals that respond to audio input. I'd love to talk.",
            upvotes: 18,
            createdAt: "2026-06-08T11:00:00Z",
          },
        ],
        createdAt: "2026-06-08T09:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Temescal",
    city: "Oakland",
    createdAt: "2026-02-01T09:00:00Z",
    isPublic: true,
    tags: ["Collaboration", "Music", "Art", "Multi-disciplinary"],
  },
  {
    id: "c9",
    name: "Urban Explorers Bay",
    description: "Hikers, cyclists, urban walkers, and anyone who wants to know their city better. Weekly walks, hidden spots, and local history.",
    coverImage: "https://picsum.photos/seed/urbanexplorers/800/400",
    emoji: "🗺️",
    category: "Outdoors",
    memberCount: 223,
    members: [
      { userId: "u8", role: "member", joinedAt: "2026-01-15T09:00:00Z" },
      { userId: "u9", role: "member", joinedAt: "2026-02-10T09:00:00Z" },
      { userId: "u13", role: "member", joinedAt: "2026-02-12T09:00:00Z" },
      { userId: "u17", role: "member", joinedAt: "2026-02-25T09:00:00Z" },
      { userId: "u18", role: "member", joinedAt: "2026-03-01T09:00:00Z" },
      { userId: "u22", role: "member", joinedAt: "2026-03-05T09:00:00Z" },
      { userId: "u26", role: "admin", joinedAt: "2026-01-25T09:00:00Z" },
    ],
    posts: [
      {
        id: "p16",
        circleId: "c9",
        authorId: "u26",
        authorName: "Kezia Atieno",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2",
        title: "Hidden staircases of SF — collective mapping project",
        body: "SF has 400+ public staircases, many with incredible views and stories. I'm mapping them all for my dissertation. Want to make this a community project — who's in?",
        category: "Discussion",
        upvotes: 58,
        replies: [
          {
            id: "r13",
            authorId: "u9",
            authorName: "Sam Park",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4",
            content: "I can build a contribution map for this. Already did something similar for CityGen. Let's talk.",
            upvotes: 24,
            createdAt: "2026-06-07T14:00:00Z",
          },
        ],
        createdAt: "2026-06-07T10:00:00Z",
        isPinned: true,
      },
    ],
    neighborhood: "Rockridge",
    city: "Oakland",
    createdAt: "2026-01-25T09:00:00Z",
    isPublic: true,
    tags: ["Hiking", "Cycling", "Urban Exploration", "Local History"],
  },
  {
    id: "c10",
    name: "Bay Area Run Club",
    description: "Runners of all paces, distances, and abilities. Weekly group runs across SF and Oakland. No one gets left behind.",
    coverImage: "https://picsum.photos/seed/bayrunclub/800/400",
    emoji: "🏃",
    category: "Fitness",
    memberCount: 267,
    members: [
      { userId: "u7", role: "member", joinedAt: "2026-01-22T09:00:00Z" },
      { userId: "u12", role: "admin", joinedAt: "2026-01-30T09:00:00Z" },
      { userId: "u14", role: "member", joinedAt: "2026-02-15T09:00:00Z" },
      { userId: "u27", role: "moderator", joinedAt: "2026-01-05T09:00:00Z" },
    ],
    posts: [
      {
        id: "p17",
        circleId: "c10",
        authorId: "u12",
        authorName: "Imani Bell",
        authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede",
        title: "Saturday 7am run — Lake Merritt loop, 8 miles",
        body: "Meeting at the pergola at the north end of the lake. Pace will be comfortable conversational — nobody's racing. Coffee after at the Grand Lake Cafe.",
        category: "Event",
        upvotes: 41,
        replies: [
          {
            id: "r14",
            authorId: "u27",
            authorName: "Felix Oduya",
            authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=felix&backgroundColor=ffd5dc",
            content: "I'll be there. I'll bring my running vest if anyone wants to store a jacket during the run.",
            upvotes: 6,
            createdAt: "2026-06-11T08:00:00Z",
          },
        ],
        createdAt: "2026-06-11T07:00:00Z",
        isPinned: false,
      },
    ],
    neighborhood: "Lake Merritt",
    city: "Oakland",
    createdAt: "2026-01-05T09:00:00Z",
    isPublic: true,
    tags: ["Running", "Fitness", "Community", "Marathon Training"],
  },
];
