import type { Event } from "@/lib/types";

export const SEED_EVENTS: Event[] = [
  {
    id: "e1",
    title: "SF AI Builders — Demos & Drinks",
    description: "Monthly demo night for AI builders. 5-minute demos, rapid feedback, and honest conversation. Founding teams, side projects, and research welcome. All skill levels, no pitch competition energy.",
    coverImage: "https://picsum.photos/seed/aidemos/800/450",
    category: "Meetup",
    hostId: "u1",
    hostName: "Maya Chen",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4",
    date: "2026-06-20",
    time: "18:30",
    endTime: "21:00",
    neighborhood: "SoMa",
    address: "340 Pine St, San Francisco",
    city: "San Francisco",
    maxAttendees: 60,
    attendees: [
      { userId: "u1", name: "Maya Chen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T10:00:00Z" },
      { userId: "u5", name: "Priya Sharma", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T11:00:00Z" },
      { userId: "u9", name: "Sam Park", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T12:00:00Z" },
      { userId: "u11", name: "Noah Goldberg", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=noah&backgroundColor=ffd5dc", rsvpAt: "2026-06-12T13:00:00Z" },
      { userId: "u13", name: "Ravi Menon", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T14:00:00Z" },
      { userId: "u21", name: "Brandon Osei", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=brandon&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T14:30:00Z" },
    ],
    circleId: "c1",
    coordinates: { lat: 37.7921, lng: -122.3991 },
    createdAt: "2026-06-05T09:00:00Z",
    tags: ["AI", "Demos", "Networking", "Startups"],
    isFeatured: true,
  },
  {
    id: "e2",
    title: "Golden Hour Photo Walk — Dogpatch to Potrero",
    description: "We'll walk from the Dogpatch waterfront through Potrero Hill, shooting as we go. Routes, spots, and a loose structure — bring whatever camera you want. We'll end at Farley's for coffee.",
    coverImage: "https://picsum.photos/seed/goldenhourwalk/800/450",
    category: "Social",
    hostId: "u6",
    hostName: "Leo Fontaine",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2",
    date: "2026-06-14",
    time: "09:00",
    endTime: "12:00",
    neighborhood: "Dogpatch",
    address: "Illinois St & 22nd St, San Francisco",
    city: "San Francisco",
    maxAttendees: 20,
    attendees: [
      { userId: "u6", name: "Leo Fontaine", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u2", name: "Jordan Pierce", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u15", name: "Marcus Webb", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=ffd5dc", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u25", name: "Andre Santos", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andre&backgroundColor=b6e3f4", rsvpAt: "2026-06-11T10:00:00Z" },
    ],
    circleId: "c4",
    coordinates: { lat: 37.7583, lng: -122.3892 },
    createdAt: "2026-06-08T09:00:00Z",
    tags: ["Photography", "Walk", "Community", "Outdoor"],
    isFeatured: false,
  },
  {
    id: "e3",
    title: "Community Dinner — East Oakland Food Hub",
    description: "A free community dinner at the East Oakland Food Hub. Capacity 80. Bring neighbors, bring questions, bring an appetite. We'll share about the hub's next phase and how you can get involved.",
    coverImage: "https://picsum.photos/seed/communitydinner/800/450",
    category: "Dinner",
    hostId: "u3",
    hostName: "Aisha Okonkwo",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede",
    date: "2026-06-21",
    time: "17:00",
    endTime: "20:00",
    neighborhood: "Fruitvale",
    address: "3801 International Blvd, Oakland",
    city: "Oakland",
    maxAttendees: 80,
    attendees: [
      { userId: "u3", name: "Aisha Okonkwo", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u7", name: "Tomás Rivera", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u19", name: "Marcus Obi", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcusobi&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T11:00:00Z" },
      { userId: "u30", name: "Rosa Delgado", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rosa&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T12:00:00Z" },
      { userId: "u12", name: "Imani Bell", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede", rsvpAt: "2026-06-11T09:00:00Z" },
    ],
    circleId: "c6",
    coordinates: { lat: 37.7699, lng: -122.2244 },
    createdAt: "2026-06-07T09:00:00Z",
    tags: ["Community", "Food", "Nonprofit", "Oakland"],
    isFeatured: true,
  },
  {
    id: "e4",
    title: "Live Music Night — Oakland Creatives",
    description: "An evening of original music, improvised sets, and collaborative sound. Oakland musicians only. Bring friends. The bar is open. No phone recording — just be here.",
    coverImage: "https://picsum.photos/seed/livemusic/800/450",
    category: "Social",
    hostId: "u4",
    hostName: "Kai Nakamura",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
    date: "2026-06-27",
    time: "19:00",
    endTime: "23:00",
    neighborhood: "Temescal",
    address: "4799 Shattuck Ave, Oakland",
    city: "Oakland",
    maxAttendees: 100,
    attendees: [
      { userId: "u4", name: "Kai Nakamura", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u10", name: "Destiny Flores", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=destiny&backgroundColor=d1f0c2", rsvpAt: "2026-06-09T10:00:00Z" },
      { userId: "u21", name: "Brandon Osei", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=brandon&backgroundColor=b6e3f4", rsvpAt: "2026-06-09T11:00:00Z" },
      { userId: "u23", name: "Jaylen Brooks", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jaylen&backgroundColor=ffd5dc", rsvpAt: "2026-06-09T12:00:00Z" },
    ],
    circleId: "c3",
    coordinates: { lat: 37.8362, lng: -122.2656 },
    createdAt: "2026-06-08T09:00:00Z",
    tags: ["Music", "Oakland", "Live", "Arts"],
    isFeatured: false,
  },
  {
    id: "e5",
    title: "SF Indie Hacker Coffee Meetup",
    description: "Casual coffee and conversation for people building things independently. No agenda, no pitches, no investors. Show up, talk about what you're making, make a friend.",
    coverImage: "https://picsum.photos/seed/indiehackers/800/450",
    category: "Coffee Chat",
    hostId: "u9",
    hostName: "Sam Park",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4",
    date: "2026-06-15",
    time: "10:00",
    endTime: "12:00",
    neighborhood: "Castro",
    address: "Philz Coffee, Castro District, San Francisco",
    city: "San Francisco",
    attendees: [
      { userId: "u9", name: "Sam Park", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u1", name: "Maya Chen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4", rsvpAt: "2026-06-11T10:00:00Z" },
      { userId: "u13", name: "Ravi Menon", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4", rsvpAt: "2026-06-11T11:00:00Z" },
      { userId: "u16", name: "Aaliyah Turner", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aaliyah&backgroundColor=c0aede", rsvpAt: "2026-06-11T12:00:00Z" },
      { userId: "u29", name: "Tyler Nguyen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tyler&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T09:00:00Z" },
    ],
    circleId: "c1",
    coordinates: { lat: 37.7609, lng: -122.4350 },
    createdAt: "2026-06-09T09:00:00Z",
    tags: ["Indie Hackers", "Coffee", "Startups", "Building"],
    isFeatured: false,
  },
  {
    id: "e6",
    title: "Climate Startup Speed Networking",
    description: "20-minute rotations with climate-tech founders, operators, and investors. Hosted by FarmLink. Come with a clear ask — we'll make time count.",
    coverImage: "https://picsum.photos/seed/climatenetting/800/450",
    category: "Meetup",
    hostId: "u5",
    hostName: "Priya Sharma",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=b6e3f4",
    date: "2026-06-25",
    time: "17:30",
    endTime: "20:30",
    neighborhood: "SoMa",
    address: "WeWork, 25 Taylor St, San Francisco",
    city: "San Francisco",
    maxAttendees: 50,
    attendees: [
      { userId: "u5", name: "Priya Sharma", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=b6e3f4", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u9", name: "Sam Park", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u11", name: "Noah Goldberg", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=noah&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T11:00:00Z" },
      { userId: "u24", name: "Claire Moreau", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=claire&backgroundColor=c0aede", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u29", name: "Tyler Nguyen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tyler&backgroundColor=b6e3f4", rsvpAt: "2026-06-12T10:00:00Z" },
    ],
    circleId: "c1",
    coordinates: { lat: 37.7826, lng: -122.4088 },
    createdAt: "2026-06-06T09:00:00Z",
    tags: ["Climate", "Startups", "Networking"],
    isFeatured: false,
  },
  {
    id: "e7",
    title: "Oakland Mutual Aid Morning — Volunteer Day",
    description: "Join 30+ neighbors at the Lake Merritt Community Garden for a morning of weeding, planting, and food donation sorting. Lunch provided. No experience needed. Just show up ready to move.",
    coverImage: "https://picsum.photos/seed/mutualaidmorning/800/450",
    category: "Volunteer",
    hostId: "u3",
    hostName: "Aisha Okonkwo",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede",
    date: "2026-06-22",
    time: "08:00",
    endTime: "13:00",
    neighborhood: "Lake Merritt",
    address: "666 Bellevue Ave, Oakland",
    city: "Oakland",
    attendees: [
      { userId: "u3", name: "Aisha Okonkwo", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u7", name: "Tomás Rivera", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=ffd5dc", rsvpAt: "2026-06-09T10:00:00Z" },
      { userId: "u10", name: "Destiny Flores", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=destiny&backgroundColor=d1f0c2", rsvpAt: "2026-06-09T11:00:00Z" },
      { userId: "u12", name: "Imani Bell", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u20", name: "Yuki Tanaka", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=yuki&backgroundColor=c0aede", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u30", name: "Rosa Delgado", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rosa&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T11:00:00Z" },
    ],
    circleId: "c6",
    coordinates: { lat: 37.8085, lng: -122.2553 },
    createdAt: "2026-06-07T09:00:00Z",
    tags: ["Volunteer", "Community", "Oakland", "Garden"],
    isFeatured: false,
  },
  {
    id: "e8",
    title: "Portfolio & Process — Designer Open Studio",
    description: "Three designers open their studios and walk through their process. Hosted by Jordan Pierce. Casual, intimate, honest. Attendance capped at 15.",
    coverImage: "https://picsum.photos/seed/designstudio/800/450",
    category: "Workshop",
    hostId: "u2",
    hostName: "Jordan Pierce",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=d1f0c2",
    date: "2026-06-18",
    time: "18:00",
    endTime: "20:30",
    neighborhood: "Hayes Valley",
    address: "Canopy SF, 360 Fell St, San Francisco",
    city: "San Francisco",
    maxAttendees: 15,
    attendees: [
      { userId: "u2", name: "Jordan Pierce", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u13", name: "Ravi Menon", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u18", name: "Sophie Laurent", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie&backgroundColor=d1f0c2", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u24", name: "Claire Moreau", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=claire&backgroundColor=c0aede", rsvpAt: "2026-06-11T10:00:00Z" },
    ],
    circleId: "c2",
    coordinates: { lat: 37.7762, lng: -122.4225 },
    createdAt: "2026-06-06T09:00:00Z",
    tags: ["Design", "Portfolio", "Workshop", "Creative"],
    isFeatured: false,
  },
  {
    id: "e9",
    title: "Oakland Sound — Collaborative Listening Session",
    description: "Bring a track, a demo, or an idea. We'll play it on the system and talk about it. Judgment-free zone. Hosted at Kai's studio in Temescal.",
    coverImage: "https://picsum.photos/seed/soundsession/800/450",
    category: "Social",
    hostId: "u4",
    hostName: "Kai Nakamura",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
    date: "2026-06-16",
    time: "20:00",
    endTime: "23:00",
    neighborhood: "Temescal",
    address: "Temescal Arts Center, 511 48th St, Oakland",
    city: "Oakland",
    maxAttendees: 25,
    attendees: [
      { userId: "u4", name: "Kai Nakamura", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u16", name: "Aaliyah Turner", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aaliyah&backgroundColor=c0aede", rsvpAt: "2026-06-09T10:00:00Z" },
      { userId: "u23", name: "Jaylen Brooks", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jaylen&backgroundColor=ffd5dc", rsvpAt: "2026-06-09T11:00:00Z" },
      { userId: "u28", name: "Naomi Hecht", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=naomi&backgroundColor=c0aede", rsvpAt: "2026-06-10T09:00:00Z" },
    ],
    circleId: "c8",
    coordinates: { lat: 37.8324, lng: -122.2640 },
    createdAt: "2026-06-08T09:00:00Z",
    tags: ["Music", "Listening", "Creative", "Oakland"],
    isFeatured: false,
  },
  {
    id: "e10",
    title: "Zine Swap & Print Fair — Dogpatch",
    description: "Bring zines to trade, buy, and sell. Printers on-site for quick risograph runs. Bring your most recent work. Free entry, zines from $1.",
    coverImage: "https://picsum.photos/seed/zineswap/800/450",
    category: "Social",
    hostId: "u6",
    hostName: "Leo Fontaine",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2",
    date: "2026-06-28",
    time: "11:00",
    endTime: "17:00",
    neighborhood: "Dogpatch",
    address: "Minnesota Street Project, 1275 Minnesota St, San Francisco",
    city: "San Francisco",
    attendees: [
      { userId: "u6", name: "Leo Fontaine", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u15", name: "Marcus Webb", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u25", name: "Andre Santos", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andre&backgroundColor=b6e3f4", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u28", name: "Naomi Hecht", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=naomi&backgroundColor=c0aede", rsvpAt: "2026-06-11T10:00:00Z" },
    ],
    circleId: "c4",
    coordinates: { lat: 37.7596, lng: -122.3892 },
    createdAt: "2026-06-09T09:00:00Z",
    tags: ["Zines", "Print", "Art", "Community"],
    isFeatured: false,
  },
  {
    id: "e11",
    title: "Urban Staircase Walk — Russian Hill to North Beach",
    description: "We'll climb 8 hidden staircases across Russian Hill and North Beach, ending with espresso at Caffe Trieste. 2-mile loop with a lot of elevation and history.",
    coverImage: "https://picsum.photos/seed/staircasewalk/800/450",
    category: "Hike",
    hostId: "u26",
    hostName: "Kezia Atieno",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2",
    date: "2026-06-14",
    time: "09:30",
    endTime: "12:00",
    neighborhood: "Russian Hill",
    address: "Macondray Lane entrance, San Francisco",
    city: "San Francisco",
    maxAttendees: 20,
    attendees: [
      { userId: "u26", name: "Kezia Atieno", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u8", name: "Zara Washington", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zara&backgroundColor=c0aede", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u16", name: "Aaliyah Turner", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aaliyah&backgroundColor=c0aede", rsvpAt: "2026-06-11T09:00:00Z" },
      { userId: "u19", name: "Marcus Obi", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcusobi&backgroundColor=ffd5dc", rsvpAt: "2026-06-11T10:00:00Z" },
      { userId: "u20", name: "Yuki Tanaka", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=yuki&backgroundColor=c0aede", rsvpAt: "2026-06-12T09:00:00Z" },
      { userId: "u22", name: "Mei Lin", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=meilin&backgroundColor=d1f0c2", rsvpAt: "2026-06-12T10:00:00Z" },
    ],
    circleId: "c9",
    coordinates: { lat: 37.8009, lng: -122.4194 },
    createdAt: "2026-06-07T09:00:00Z",
    tags: ["Walk", "Urban", "History", "SF"],
    isFeatured: false,
  },
  {
    id: "e12",
    title: "Filipino-Mexican Pop-Up Dinner",
    description: "A 4-course pop-up dinner by Elena Vasquez featuring recipes from her upcoming cookbook. 12 seats. BYOB. An evening of food, story, and unexpected flavor combinations.",
    coverImage: "https://picsum.photos/seed/popupdinner/800/450",
    category: "Dinner",
    hostId: "u14",
    hostName: "Elena Vasquez",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=d1f0c2",
    date: "2026-06-19",
    time: "18:30",
    endTime: "21:30",
    neighborhood: "Grand Lake",
    address: "Elena's home kitchen, Grand Lake, Oakland",
    city: "Oakland",
    maxAttendees: 12,
    attendees: [
      { userId: "u14", name: "Elena Vasquez", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=d1f0c2", rsvpAt: "2026-06-08T09:00:00Z" },
      { userId: "u3", name: "Aisha Okonkwo", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u17", name: "Daniel Kim", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=daniel&backgroundColor=b6e3f4", rsvpAt: "2026-06-09T10:00:00Z" },
    ],
    circleId: "c5",
    coordinates: { lat: 37.8147, lng: -122.2310 },
    createdAt: "2026-06-06T09:00:00Z",
    tags: ["Food", "Dinner", "Pop-up", "Filipino", "Mexican"],
    isFeatured: true,
  },
  {
    id: "e13",
    title: "Lake Merritt 8-Mile Group Run",
    description: "Weekly Saturday morning group run. Two pace groups: 9-10 min/mile and 11-12 min/mile. We finish together. Coffee at Grand Lake Cafe. Dog-friendly.",
    coverImage: "https://picsum.photos/seed/lakemerrittrun/800/450",
    category: "Hike",
    hostId: "u12",
    hostName: "Imani Bell",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede",
    date: "2026-06-14",
    time: "07:00",
    endTime: "09:30",
    neighborhood: "Lake Merritt",
    address: "Lake Merritt Pergola, 568 Bellevue Ave, Oakland",
    city: "Oakland",
    attendees: [
      { userId: "u12", name: "Imani Bell", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u26", name: "Kezia Atieno", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T10:00:00Z" },
      { userId: "u27", name: "Felix Oduya", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=felix&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T11:00:00Z" },
    ],
    circleId: "c10",
    coordinates: { lat: 37.8066, lng: -122.2559 },
    createdAt: "2026-06-08T09:00:00Z",
    tags: ["Running", "Fitness", "Oakland", "Weekend"],
    isFeatured: false,
  },
  {
    id: "e14",
    title: "Richmond Ramen Crawl — 4 Stops, 1 Night",
    description: "We hit 4 ramen spots in the Inner and Outer Richmond in one evening. Expect different bowls at each stop. Small group, max 10. We split everything.",
    coverImage: "https://picsum.photos/seed/ramencrawl/800/450",
    category: "Social",
    hostId: "u17",
    hostName: "Daniel Kim",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=daniel&backgroundColor=b6e3f4",
    date: "2026-06-17",
    time: "18:00",
    endTime: "22:00",
    neighborhood: "Richmond",
    address: "Inner Richmond, San Francisco (full route shared on RSVP)",
    city: "San Francisco",
    maxAttendees: 10,
    attendees: [
      { userId: "u17", name: "Daniel Kim", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=daniel&backgroundColor=b6e3f4", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u14", name: "Elena Vasquez", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=d1f0c2", rsvpAt: "2026-06-09T10:00:00Z" },
    ],
    circleId: "c5",
    coordinates: { lat: 37.7787, lng: -122.4663 },
    createdAt: "2026-06-09T09:00:00Z",
    tags: ["Food", "Ramen", "Social", "SF"],
    isFeatured: false,
  },
  {
    id: "e15",
    title: "Bay Area Writers — Open Reading Night",
    description: "Read a poem, a paragraph, a chapter, or nothing. All levels, all genres. Hosted at Pegasus Books in Rockridge. 3 minutes per reader. Warm and serious in equal measure.",
    coverImage: "https://picsum.photos/seed/writersreading/800/450",
    category: "Social",
    hostId: "u8",
    hostName: "Zara Washington",
    hostAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zara&backgroundColor=c0aede",
    date: "2026-06-23",
    time: "19:00",
    endTime: "21:30",
    neighborhood: "Rockridge",
    address: "Pegasus Books, 5560 College Ave, Oakland",
    city: "Oakland",
    attendees: [
      { userId: "u8", name: "Zara Washington", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zara&backgroundColor=c0aede", rsvpAt: "2026-06-09T09:00:00Z" },
      { userId: "u18", name: "Sophie Laurent", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie&backgroundColor=d1f0c2", rsvpAt: "2026-06-09T10:00:00Z" },
      { userId: "u22", name: "Mei Lin", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=meilin&backgroundColor=d1f0c2", rsvpAt: "2026-06-10T09:00:00Z" },
      { userId: "u27", name: "Felix Oduya", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=felix&backgroundColor=ffd5dc", rsvpAt: "2026-06-10T10:00:00Z" },
    ],
    circleId: "c7",
    coordinates: { lat: 37.8454, lng: -122.2510 },
    createdAt: "2026-06-08T09:00:00Z",
    tags: ["Writing", "Reading", "Oakland", "Literary"],
    isFeatured: false,
  },
];
