import type { User } from "@/lib/types";

export const SEED_USERS: User[] = [
  {
    id: "u1",
    name: "Maya Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4",
    profession: "Software Engineer",
    neighborhood: "Mission",
    city: "San Francisco",
    bio: "Building AI tools for creative people. Ex-Figma, now indie hacking. I care deeply about products that feel human.",
    personalityPrompt: "Will travel 30 minutes for a great croissant.",
    currentlyInto: "Building an AI writing tool for journalists",
    currentlyIntoUpdatedAt: "2026-06-11T09:00:00Z",
    interests: ["AI", "Startups", "Coffee", "Books"],
    lookingFor: ["Collaborators", "Coffee Chats"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7599, lng: -122.4148 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 210, connector: 85, neighbor: 120, total: 415 },
    badges: [
      { type: "seven_day_streak", earnedAt: "2026-05-01", label: "7-Day Streak", emoji: "🔥" },
      { type: "showcase_star", earnedAt: "2026-04-15", label: "Showcase Star", emoji: "✨" },
      { type: "early_member", earnedAt: "2026-01-10", label: "Early Member", emoji: "🐣" },
    ],
    streakCount: 23,
    lastActive: "2026-06-12T08:30:00Z",
    showcaseItems: [
      {
        id: "s1",
        title: "Journo AI",
        category: "Software",
        coverImage: "https://picsum.photos/seed/journoai/600/400",
        description: "An AI-powered research and drafting tool built for investigative journalists. Cuts research time by 60%.",
        link: "https://journo.ai",
        reactions: { collab: 14, inspired: 32, feedback: 8 },
        createdAt: "2026-04-10T12:00:00Z",
      },
      {
        id: "s2",
        title: "Mission Street Photo Series",
        category: "Photography",
        coverImage: "https://picsum.photos/seed/missionstreet/600/400",
        description: "A 30-day documentary project capturing daily life on Mission Street.",
        reactions: { collab: 3, inspired: 47, feedback: 5 },
        createdAt: "2026-03-01T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v1", giverId: "u3", giverName: "Aisha Okonkwo", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", type: "Great Collaborator", note: "Maya shipped our entire frontend in a weekend. Unreal.", createdAt: "2026-05-20T10:00:00Z" },
    ],
    circleIds: ["c1", "c2"],
    eventIds: ["e1", "e5"],
    joinedAt: "2026-01-10T09:00:00Z",
    isCurrentUser: true,
  },
  {
    id: "u2",
    name: "Jordan Pierce",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=d1f0c2",
    profession: "Designer",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    bio: "Product designer obsessed with motion and tactile UI. Currently freelancing after 4 years at Airbnb.",
    personalityPrompt: "Ask me about design systems that actually work.",
    currentlyInto: "Redesigning my portfolio site from scratch",
    currentlyIntoUpdatedAt: "2026-06-10T14:00:00Z",
    interests: ["Design", "Coffee", "Photography", "Art"],
    lookingFor: ["Creative Feedback", "Collaborators", "Friends"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7762, lng: -122.4232 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 175, connector: 95, neighbor: 80, total: 350 },
    badges: [
      { type: "seven_day_streak", earnedAt: "2026-05-10", label: "7-Day Streak", emoji: "🔥" },
      { type: "connector", earnedAt: "2026-04-20", label: "Connector", emoji: "🔗" },
    ],
    streakCount: 11,
    lastActive: "2026-06-11T19:00:00Z",
    showcaseItems: [
      {
        id: "s3",
        title: "Airbnb Design System 2.0",
        category: "Design",
        coverImage: "https://picsum.photos/seed/airbnbds/600/400",
        description: "Led the redesign of Airbnb's internal component library — 400+ components, 12 teams.",
        reactions: { collab: 5, inspired: 61, feedback: 19 },
        createdAt: "2026-02-14T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v2", giverId: "u1", giverName: "Maya Chen", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4", type: "Creative Inspiration", note: "Jordan's taste is impeccable — just follow their aesthetic.", createdAt: "2026-05-25T10:00:00Z" },
    ],
    circleIds: ["c2", "c4"],
    eventIds: ["e2", "e8"],
    joinedAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "u3",
    name: "Aisha Okonkwo",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede",
    profession: "Nonprofit",
    neighborhood: "Fruitvale",
    city: "Oakland",
    bio: "Running a food security nonprofit in East Oakland. Former Google PM. I believe in radical community care.",
    personalityPrompt: "I host dinners. Ask me about the next one.",
    currentlyInto: "Planning a community garden fundraiser",
    currentlyIntoUpdatedAt: "2026-06-12T07:00:00Z",
    interests: ["Volunteering", "Food", "Local Events", "Sustainability"],
    lookingFor: ["Community", "Project Partners", "Collaborators"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7749, lng: -122.2256 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 90, connector: 210, neighbor: 280, total: 580 },
    badges: [
      { type: "first_event_hosted", earnedAt: "2026-02-01", label: "First Event Hosted", emoji: "🏠" },
      { type: "community_pillar", earnedAt: "2026-05-01", label: "Community Pillar", emoji: "🌟" },
      { type: "hundred_days", earnedAt: "2026-05-15", label: "100 Days in Cove", emoji: "🏅" },
      { type: "vouched_ten", earnedAt: "2026-04-10", label: "Vouched 10 People", emoji: "🤝" },
    ],
    streakCount: 41,
    lastActive: "2026-06-12T07:00:00Z",
    showcaseItems: [
      {
        id: "s4",
        title: "East Oakland Food Hub",
        category: "Nonprofit",
        coverImage: "https://picsum.photos/seed/foodhub/600/400",
        description: "Distributing 2,000+ meals/week through a network of 8 community kitchens. Zero food waste model.",
        reactions: { collab: 22, inspired: 89, feedback: 11 },
        createdAt: "2026-03-20T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v3", giverId: "u7", giverName: "Tomás Rivera", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=ffd5dc", type: "Met IRL", note: "Met at a community event. Aisha is the real deal.", createdAt: "2026-04-15T10:00:00Z" },
    ],
    circleIds: ["c5", "c6"],
    eventIds: ["e3", "e7", "e12"],
    joinedAt: "2026-01-20T09:00:00Z",
  },
  {
    id: "u4",
    name: "Kai Nakamura",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc",
    profession: "Musician",
    neighborhood: "Temescal",
    city: "Oakland",
    bio: "Jazz drummer turned lo-fi producer. I make music for people who think too much at 2am.",
    personalityPrompt: "Currently learning pottery and failing gloriously.",
    currentlyInto: "Recording an EP in my bedroom studio",
    currentlyIntoUpdatedAt: "2026-06-09T22:00:00Z",
    interests: ["Music", "Art", "Coffee", "Film"],
    lookingFor: ["Collaborators", "Creative Feedback", "Friends"],
    availability: "Open to Chat",
    coordinates: { lat: 37.8324, lng: -122.2627 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 150, connector: 60, neighbor: 95, total: 305 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-04-01", label: "Showcase Star", emoji: "✨" },
      { type: "circle_founder", earnedAt: "2026-02-15", label: "Circle Founder", emoji: "🌱" },
    ],
    streakCount: 7,
    lastActive: "2026-06-12T01:00:00Z",
    showcaseItems: [
      {
        id: "s5",
        title: "Midnight Signals EP",
        category: "Music",
        coverImage: "https://picsum.photos/seed/midnightsignals/600/400",
        description: "4-track lo-fi jazz EP recorded in a converted Oakland warehouse. Stream on Bandcamp.",
        link: "https://kaination.bandcamp.com",
        reactions: { collab: 8, inspired: 53, feedback: 14 },
        createdAt: "2026-03-10T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c3", "c8"],
    eventIds: ["e4", "e9"],
    joinedAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "u5",
    name: "Priya Sharma",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=b6e3f4",
    profession: "Founder",
    neighborhood: "SoMa",
    city: "San Francisco",
    bio: "Building Cove's favorite competitor (jk). Founder of a climate-tech startup connecting urban farmers to restaurants.",
    personalityPrompt: "I probably have a spreadsheet for that.",
    currentlyInto: "Closing our seed round — $1.2M and counting",
    currentlyIntoUpdatedAt: "2026-06-11T16:00:00Z",
    interests: ["Startups", "Sustainability", "Food", "AI"],
    lookingFor: ["Project Partners", "Mentorship", "Coffee Chats"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7785, lng: -122.3986 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 200, connector: 130, neighbor: 70, total: 400 },
    badges: [
      { type: "connector", earnedAt: "2026-04-05", label: "Connector", emoji: "🔗" },
      { type: "seven_day_streak", earnedAt: "2026-05-20", label: "7-Day Streak", emoji: "🔥" },
    ],
    streakCount: 15,
    lastActive: "2026-06-12T11:00:00Z",
    showcaseItems: [
      {
        id: "s6",
        title: "FarmLink — Urban Food Logistics",
        category: "Software",
        coverImage: "https://picsum.photos/seed/farmlink/600/400",
        description: "Connecting 80+ urban farms to 200+ Bay Area restaurants. $4M in GMV in year one.",
        reactions: { collab: 18, inspired: 44, feedback: 22 },
        createdAt: "2026-03-15T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v5", giverId: "u1", giverName: "Maya Chen", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya&backgroundColor=b6e3f4", type: "Great Collaborator", note: "Priya ships faster than anyone I know.", createdAt: "2026-05-15T10:00:00Z" },
    ],
    circleIds: ["c1", "c6"],
    eventIds: ["e1", "e6"],
    joinedAt: "2026-01-25T09:00:00Z",
  },
  {
    id: "u6",
    name: "Leo Fontaine",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=leo&backgroundColor=d1f0c2",
    profession: "Photographer",
    neighborhood: "Dogpatch",
    city: "San Francisco",
    bio: "Documentary photographer and visual storyteller. I shoot everything from $10 burritos to $10M startups.",
    personalityPrompt: "The best light is always 20 minutes after you give up.",
    currentlyInto: "Shooting a portrait series on Bay Area street vendors",
    currentlyIntoUpdatedAt: "2026-06-10T18:00:00Z",
    interests: ["Photography", "Art", "Food", "Travel"],
    lookingFor: ["Creative Feedback", "Collaborators", "Friends"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7583, lng: -122.3892 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 180, connector: 70, neighbor: 60, total: 310 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-03-20", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 5,
    lastActive: "2026-06-11T20:00:00Z",
    showcaseItems: [
      {
        id: "s7",
        title: "Vendors of the Bay",
        category: "Photography",
        coverImage: "https://picsum.photos/seed/vendors/600/400",
        description: "An ongoing portrait series celebrating the street vendors, food cart operators, and market sellers who feed our cities.",
        reactions: { collab: 4, inspired: 72, feedback: 9 },
        createdAt: "2026-02-20T12:00:00Z",
      },
      {
        id: "s8",
        title: "Startup Portraits",
        category: "Photography",
        coverImage: "https://picsum.photos/seed/startupportraits/600/400",
        description: "Behind-the-scenes photo series inside 12 SF startups — the real faces behind the pitch decks.",
        reactions: { collab: 7, inspired: 38, feedback: 5 },
        createdAt: "2026-01-15T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c4", "c8"],
    eventIds: ["e2", "e10"],
    joinedAt: "2026-02-05T09:00:00Z",
  },
  {
    id: "u7",
    name: "Tomás Rivera",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tomas&backgroundColor=ffd5dc",
    profession: "Marketer",
    neighborhood: "Mission",
    city: "San Francisco",
    bio: "Growth marketer who grew up in the Mission. I help local businesses compete with the chains.",
    personalityPrompt: "Ask me about the best taquerias you've never heard of.",
    currentlyInto: "Learning ceramics at Potrero Hill Clay Studio",
    currentlyIntoUpdatedAt: "2026-06-08T12:00:00Z",
    interests: ["Food", "Local Events", "Art", "Startups"],
    lookingFor: ["Collaborators", "Community", "Friends"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7599, lng: -122.4183 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 95, connector: 155, neighbor: 180, total: 430 },
    badges: [
      { type: "connector", earnedAt: "2026-04-01", label: "Connector", emoji: "🔗" },
      { type: "first_event_hosted", earnedAt: "2026-03-15", label: "First Event Hosted", emoji: "🏠" },
    ],
    streakCount: 19,
    lastActive: "2026-06-12T09:00:00Z",
    showcaseItems: [
      {
        id: "s9",
        title: "Mission Small Business Campaign",
        category: "Marketing",
        coverImage: "https://picsum.photos/seed/missionbiz/600/400",
        description: "A hyper-local marketing campaign that helped 15 Mission district businesses increase revenue 30% YoY.",
        reactions: { collab: 11, inspired: 29, feedback: 16 },
        createdAt: "2026-03-01T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v7", giverId: "u3", giverName: "Aisha Okonkwo", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", type: "Community Builder", note: "Tomás shows up for the neighborhood in ways that matter.", createdAt: "2026-05-01T10:00:00Z" },
    ],
    circleIds: ["c5", "c6", "c10"],
    eventIds: ["e3", "e7"],
    joinedAt: "2026-01-22T09:00:00Z",
  },
  {
    id: "u8",
    name: "Zara Washington",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zara&backgroundColor=c0aede",
    profession: "Writer",
    neighborhood: "Rockridge",
    city: "Oakland",
    bio: "Journalist and essayist covering urban culture, housing, and the Bay Area's identity crisis. Published in The Atlantic and SF Chronicle.",
    personalityPrompt: "I have strong opinions about what makes a neighborhood a neighborhood.",
    currentlyInto: "Writing a longform piece on Oakland's gentrification",
    currentlyIntoUpdatedAt: "2026-06-12T10:00:00Z",
    interests: ["Books", "Local Events", "Art", "Sustainability"],
    lookingFor: ["Community", "Creative Feedback", "Friends"],
    availability: "Open to Chat",
    coordinates: { lat: 37.8454, lng: -122.2508 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 160, connector: 80, neighbor: 130, total: 370 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-04-20", label: "Showcase Star", emoji: "✨" },
      { type: "early_member", earnedAt: "2026-01-15", label: "Early Member", emoji: "🐣" },
    ],
    streakCount: 9,
    lastActive: "2026-06-12T10:00:00Z",
    showcaseItems: [
      {
        id: "s10",
        title: "The Last Affordable City",
        category: "Writing",
        coverImage: "https://picsum.photos/seed/lastcity/600/400",
        description: "A series of essays on what Oakland is losing and what it's fighting to keep. Featured in The Atlantic.",
        link: "https://theatlantic.com",
        reactions: { collab: 2, inspired: 94, feedback: 21 },
        createdAt: "2026-03-25T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c7", "c9"],
    eventIds: ["e11", "e15"],
    joinedAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "u9",
    name: "Sam Park",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam&backgroundColor=b6e3f4",
    profession: "Software Engineer",
    neighborhood: "Castro",
    city: "San Francisco",
    bio: "Staff engineer at Stripe. I work on infra during the day and build dumb fun apps at night. Current obsession: procedural map generation.",
    personalityPrompt: "Deployed to prod at midnight more times than I'd like to admit.",
    currentlyInto: "Building a procedural city map generator",
    currentlyIntoUpdatedAt: "2026-06-11T23:00:00Z",
    interests: ["AI", "Startups", "Gaming", "Coffee"],
    lookingFor: ["Project Partners", "Friends", "Coffee Chats"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7609, lng: -122.4350 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 220, connector: 55, neighbor: 65, total: 340 },
    badges: [
      { type: "seven_day_streak", earnedAt: "2026-05-05", label: "7-Day Streak", emoji: "🔥" },
      { type: "showcase_star", earnedAt: "2026-04-10", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 14,
    lastActive: "2026-06-12T00:00:00Z",
    showcaseItems: [
      {
        id: "s11",
        title: "CityGen",
        category: "Software",
        coverImage: "https://picsum.photos/seed/citygen/600/400",
        description: "Procedural city map generator that creates believable urban layouts. 10k GitHub stars in 3 months.",
        link: "https://github.com/samparkdev/citygen",
        reactions: { collab: 31, inspired: 67, feedback: 18 },
        createdAt: "2026-02-28T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c9"],
    eventIds: ["e5", "e6"],
    joinedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "u10",
    name: "Destiny Flores",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=destiny&backgroundColor=d1f0c2",
    profession: "Artist",
    neighborhood: "Uptown",
    city: "Oakland",
    bio: "Muralist and installation artist. My work lives at the intersection of grief, joy, and color theory.",
    personalityPrompt: "I'm always covered in paint. It's a personality trait.",
    currentlyInto: "Working on a 40-foot mural for the new Fruitvale transit hub",
    currentlyIntoUpdatedAt: "2026-06-12T08:00:00Z",
    interests: ["Art", "Local Events", "Music", "Sustainability"],
    lookingFor: ["Community", "Creative Feedback", "Collaborators"],
    availability: "Attending Events",
    coordinates: { lat: 37.8080, lng: -122.2695 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 195, connector: 110, neighbor: 200, total: 505 },
    badges: [
      { type: "community_pillar", earnedAt: "2026-05-15", label: "Community Pillar", emoji: "🌟" },
      { type: "first_event_hosted", earnedAt: "2026-03-01", label: "First Event Hosted", emoji: "🏠" },
      { type: "circle_founder", earnedAt: "2026-02-20", label: "Circle Founder", emoji: "🌱" },
    ],
    streakCount: 33,
    lastActive: "2026-06-12T08:00:00Z",
    showcaseItems: [
      {
        id: "s12",
        title: "Fruitvale Transit Hub Mural",
        category: "Art",
        coverImage: "https://picsum.photos/seed/fruitvalemural/600/400",
        description: "A 40-foot mural celebrating Oakland's Latinx and African American communities at the Fruitvale BART station.",
        reactions: { collab: 9, inspired: 121, feedback: 8 },
        createdAt: "2026-05-01T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v10", giverId: "u4", giverName: "Kai Nakamura", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kai&backgroundColor=ffd5dc", type: "Creative Inspiration", note: "Destiny's work genuinely changed how I think about space.", createdAt: "2026-05-10T10:00:00Z" },
    ],
    circleIds: ["c3", "c5"],
    eventIds: ["e4", "e7"],
    joinedAt: "2026-01-28T09:00:00Z",
  },
  {
    id: "u11",
    name: "Noah Goldberg",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=noah&backgroundColor=ffd5dc",
    profession: "Founder",
    neighborhood: "Marina",
    city: "San Francisco",
    bio: "3x founder. Currently building a mental health platform for first-gen college students. I believe in product-led everything.",
    personalityPrompt: "My therapist told me to slow down. I'm working on it (by building another startup).",
    currentlyInto: "Launching a beta for 500 SFSU students next week",
    currentlyIntoUpdatedAt: "2026-06-12T11:00:00Z",
    interests: ["Startups", "AI", "Fitness", "Books"],
    lookingFor: ["Mentorship", "Coffee Chats", "Project Partners"],
    availability: "Open to Chat",
    coordinates: { lat: 37.8030, lng: -122.4377 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 230, connector: 140, neighbor: 50, total: 420 },
    badges: [
      { type: "connector", earnedAt: "2026-04-10", label: "Connector", emoji: "🔗" },
      { type: "seven_day_streak", earnedAt: "2026-05-25", label: "7-Day Streak", emoji: "🔥" },
    ],
    streakCount: 28,
    lastActive: "2026-06-12T11:00:00Z",
    showcaseItems: [
      {
        id: "s13",
        title: "Anchor — Mental Health for Students",
        category: "Software",
        coverImage: "https://picsum.photos/seed/anchor/600/400",
        description: "A peer support and therapy-matching app built for first-gen college students. 2,000 waitlist signups in 2 weeks.",
        reactions: { collab: 15, inspired: 48, feedback: 27 },
        createdAt: "2026-04-20T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c7"],
    eventIds: ["e1", "e6"],
    joinedAt: "2026-02-08T09:00:00Z",
  },
  {
    id: "u12",
    name: "Imani Bell",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=imani&backgroundColor=c0aede",
    profession: "Fitness",
    neighborhood: "Lake Merritt",
    city: "Oakland",
    bio: "Personal trainer, group fitness instructor, and certified nutritionist. I help people find joy in moving their bodies.",
    personalityPrompt: "Training for a marathon and I will bring it up.",
    currentlyInto: "Training for my third marathon — Oakland in November",
    currentlyIntoUpdatedAt: "2026-06-11T06:00:00Z",
    interests: ["Fitness", "Hiking", "Food", "Local Events"],
    lookingFor: ["Community", "Friends", "Collaborators"],
    availability: "Open to Meet",
    coordinates: { lat: 37.8085, lng: -122.2600 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 80, connector: 170, neighbor: 190, total: 440 },
    badges: [
      { type: "first_event_hosted", earnedAt: "2026-03-10", label: "First Event Hosted", emoji: "🏠" },
      { type: "connector", earnedAt: "2026-05-01", label: "Connector", emoji: "🔗" },
      { type: "thirty_day_streak", earnedAt: "2026-05-20", label: "30-Day Streak", emoji: "💫" },
    ],
    streakCount: 52,
    lastActive: "2026-06-12T06:30:00Z",
    showcaseItems: [
      {
        id: "s14",
        title: "Move Oakland",
        category: "Fitness",
        coverImage: "https://picsum.photos/seed/moveoakland/600/400",
        description: "A community fitness program bringing free weekly outdoor workouts to underserved Oakland neighborhoods. 400+ participants.",
        reactions: { collab: 16, inspired: 75, feedback: 6 },
        createdAt: "2026-03-05T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v12", giverId: "u3", giverName: "Aisha Okonkwo", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aisha&backgroundColor=c0aede", type: "Community Builder", note: "Imani is the reason our neighborhood actually moves together.", createdAt: "2026-05-15T10:00:00Z" },
    ],
    circleIds: ["c6", "c10"],
    eventIds: ["e7", "e13"],
    joinedAt: "2026-01-30T09:00:00Z",
  },
  {
    id: "u13",
    name: "Ravi Menon",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ravi&backgroundColor=b6e3f4",
    profession: "Software Engineer",
    neighborhood: "Nob Hill",
    city: "San Francisco",
    bio: "ML engineer at Anthropic working on alignment. Cares about AI safety, good ramen, and his houseplants.",
    personalityPrompt: "Ask me about the AI timelines discourse. I dare you.",
    currentlyInto: "Reading about interpretability research",
    currentlyIntoUpdatedAt: "2026-06-10T21:00:00Z",
    interests: ["AI", "Books", "Coffee", "Hiking"],
    lookingFor: ["Friends", "Coffee Chats", "Community"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7930, lng: -122.4133 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 170, connector: 65, neighbor: 90, total: 325 },
    badges: [
      { type: "seven_day_streak", earnedAt: "2026-05-08", label: "7-Day Streak", emoji: "🔥" },
      { type: "showcase_star", earnedAt: "2026-03-15", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 18,
    lastActive: "2026-06-11T22:00:00Z",
    showcaseItems: [
      {
        id: "s15",
        title: "Mechanistic Interpretability Primer",
        category: "Writing",
        coverImage: "https://picsum.photos/seed/interpretability/600/400",
        description: "An accessible deep-dive into how transformer models actually work. 50k readers, translated into 8 languages.",
        link: "https://ravimenon.substack.com",
        reactions: { collab: 7, inspired: 88, feedback: 31 },
        createdAt: "2026-02-10T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c9"],
    eventIds: ["e5", "e8"],
    joinedAt: "2026-02-12T09:00:00Z",
  },
  {
    id: "u14",
    name: "Elena Vasquez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=d1f0c2",
    profession: "Food Creator",
    neighborhood: "Grand Lake",
    city: "Oakland",
    bio: "Recipe developer and food stylist. I make Filipino-Mexican fusion food and my abuela has strong opinions about it.",
    personalityPrompt: "The secret ingredient is always more garlic.",
    currentlyInto: "Developing a cookbook proposal",
    currentlyIntoUpdatedAt: "2026-06-11T15:00:00Z",
    interests: ["Food", "Photography", "Art", "Travel"],
    lookingFor: ["Collaborators", "Creative Feedback", "Community"],
    availability: "Open to Meet",
    coordinates: { lat: 37.8147, lng: -122.2330 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 145, connector: 90, neighbor: 110, total: 345 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-04-05", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 12,
    lastActive: "2026-06-12T12:00:00Z",
    showcaseItems: [
      {
        id: "s16",
        title: "Lola's Fusion Kitchen",
        category: "Food",
        coverImage: "https://picsum.photos/seed/lolasfusion/600/400",
        description: "A food blog and recipe series exploring Filipino-Mexican fusion. 80k Instagram followers, 2 Zagat mentions.",
        link: "https://lolasfusion.com",
        reactions: { collab: 12, inspired: 66, feedback: 9 },
        createdAt: "2026-03-20T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c5", "c10"],
    eventIds: ["e12", "e14"],
    joinedAt: "2026-02-15T09:00:00Z",
  },
  {
    id: "u15",
    name: "Marcus Webb",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=ffd5dc",
    profession: "Designer",
    neighborhood: "Potrero Hill",
    city: "San Francisco",
    bio: "Brand identity designer. I've built visual identities for 30+ startups. I'm picky about fonts and I'm not sorry.",
    personalityPrompt: "That's not a typeface, it's a personality disorder.",
    currentlyInto: "Redesigning a nonprofit's entire brand identity",
    currentlyIntoUpdatedAt: "2026-06-09T17:00:00Z",
    interests: ["Design", "Art", "Coffee", "Books"],
    lookingFor: ["Creative Feedback", "Collaborators"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7616, lng: -122.3983 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 190, connector: 75, neighbor: 55, total: 320 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-04-25", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 6,
    lastActive: "2026-06-10T18:00:00Z",
    showcaseItems: [
      {
        id: "s17",
        title: "Soleil Collective Brand Identity",
        category: "Design",
        coverImage: "https://picsum.photos/seed/soleil/600/400",
        description: "Complete brand identity for an Oakland-based art collective — logo, palette, type system, and print materials.",
        reactions: { collab: 6, inspired: 49, feedback: 22 },
        createdAt: "2026-04-01T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c2", "c8"],
    eventIds: ["e2", "e10"],
    joinedAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "u16",
    name: "Aaliyah Turner",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aaliyah&backgroundColor=c0aede",
    profession: "Student",
    neighborhood: "Haight-Ashbury",
    city: "San Francisco",
    bio: "CS + Art double major at SFSU. Building weird things at the intersection of code and creativity. President of the Maker Club.",
    personalityPrompt: "Accidentally broke the university's wifi with my thesis project.",
    currentlyInto: "Building an AR street art app for my senior thesis",
    currentlyIntoUpdatedAt: "2026-06-12T09:00:00Z",
    interests: ["AI", "Art", "Gaming", "Music"],
    lookingFor: ["Mentorship", "Collaborators", "Friends"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7694, lng: -122.4474 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 110, connector: 80, neighbor: 100, total: 290 },
    badges: [
      { type: "early_member", earnedAt: "2026-01-20", label: "Early Member", emoji: "🐣" },
    ],
    streakCount: 21,
    lastActive: "2026-06-12T09:00:00Z",
    showcaseItems: [
      {
        id: "s18",
        title: "StreetLayer AR App",
        category: "Software",
        coverImage: "https://picsum.photos/seed/streetlayer/600/400",
        description: "An augmented reality app that lets users discover and add layers of hidden art to city walls.",
        reactions: { collab: 19, inspired: 34, feedback: 13 },
        createdAt: "2026-05-10T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c3", "c4"],
    eventIds: ["e5", "e9", "e11"],
    joinedAt: "2026-01-20T09:00:00Z",
  },
  {
    id: "u17",
    name: "Daniel Kim",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=daniel&backgroundColor=b6e3f4",
    profession: "Software Engineer",
    neighborhood: "Richmond",
    city: "San Francisco",
    bio: "Backend engineer at a Series B climate startup. Runs a biweekly Korean BBQ dinner for 12 people. Very selective invite list.",
    personalityPrompt: "My dinner table is my lab. You're either studying cuisine or being studied.",
    currentlyInto: "Exploring good ramen spots in the Richmond",
    currentlyIntoUpdatedAt: "2026-06-11T20:00:00Z",
    interests: ["Food", "Coffee", "Hiking", "Books"],
    lookingFor: ["Friends", "Community"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7787, lng: -122.4663 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 100, connector: 120, neighbor: 160, total: 380 },
    badges: [
      { type: "first_event_hosted", earnedAt: "2026-04-01", label: "First Event Hosted", emoji: "🏠" },
      { type: "connector", earnedAt: "2026-05-15", label: "Connector", emoji: "🔗" },
    ],
    streakCount: 16,
    lastActive: "2026-06-12T07:00:00Z",
    showcaseItems: [],
    vouches: [],
    circleIds: ["c5", "c9"],
    eventIds: ["e12", "e14"],
    joinedAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "u18",
    name: "Sophie Laurent",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie&backgroundColor=d1f0c2",
    profession: "Marketer",
    neighborhood: "Castro",
    city: "San Francisco",
    bio: "Brand strategist and content lead at a climate-tech scale-up. French-American, obsessed with narrative.",
    personalityPrompt: "Can turn any product into a story worth caring about.",
    currentlyInto: "Reading Ursula Le Guin for the fourth time",
    currentlyIntoUpdatedAt: "2026-06-10T22:00:00Z",
    interests: ["Books", "Fashion", "Coffee", "Travel"],
    lookingFor: ["Friends", "Coffee Chats", "Creative Feedback"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7609, lng: -122.4349 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 120, connector: 100, neighbor: 80, total: 300 },
    badges: [
      { type: "seven_day_streak", earnedAt: "2026-05-18", label: "7-Day Streak", emoji: "🔥" },
    ],
    streakCount: 8,
    lastActive: "2026-06-11T21:00:00Z",
    showcaseItems: [
      {
        id: "s19",
        title: "The Climate Narrative Project",
        category: "Marketing",
        coverImage: "https://picsum.photos/seed/climatenarratives/600/400",
        description: "A content strategy framework for climate brands that want to inspire action without fearmongering.",
        reactions: { collab: 8, inspired: 41, feedback: 14 },
        createdAt: "2026-04-10T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c7", "c9"],
    eventIds: ["e8", "e15"],
    joinedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "u19",
    name: "Marcus Obi",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcusobi&backgroundColor=ffd5dc",
    profession: "Nonprofit",
    neighborhood: "Tenderloin",
    city: "San Francisco",
    bio: "Co-founder of a housing advocacy org in the Tenderloin. Former public defender. Fighting displacement one policy at a time.",
    personalityPrompt: "Ask me about tenant rights. I'll probably give you a ten-minute lecture.",
    currentlyInto: "Organizing against a new eviction wave in SoMa",
    currentlyIntoUpdatedAt: "2026-06-12T08:00:00Z",
    interests: ["Volunteering", "Local Events", "Sustainability", "Books"],
    lookingFor: ["Community", "Project Partners", "Collaborators"],
    availability: "Attending Events",
    coordinates: { lat: 37.7836, lng: -122.4133 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 85, connector: 160, neighbor: 240, total: 485 },
    badges: [
      { type: "community_pillar", earnedAt: "2026-05-20", label: "Community Pillar", emoji: "🌟" },
      { type: "vouched_ten", earnedAt: "2026-04-20", label: "Vouched 10 People", emoji: "🤝" },
    ],
    streakCount: 25,
    lastActive: "2026-06-12T08:00:00Z",
    showcaseItems: [
      {
        id: "s20",
        title: "Tenderloin Housing Coalition",
        category: "Nonprofit",
        coverImage: "https://picsum.photos/seed/tlhousing/600/400",
        description: "A coalition of 12 orgs fighting housing displacement in SF's most vulnerable neighborhoods.",
        reactions: { collab: 20, inspired: 58, feedback: 7 },
        createdAt: "2026-03-10T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c6", "c7"],
    eventIds: ["e3", "e11"],
    joinedAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "u20",
    name: "Yuki Tanaka",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=yuki&backgroundColor=c0aede",
    profession: "Designer",
    neighborhood: "Temescal",
    city: "Oakland",
    bio: "UX researcher and service designer. I map how communities work so we can build better ones. Part-time ceramics teacher.",
    personalityPrompt: "Currently learning pottery and teaching everyone I know.",
    currentlyInto: "Running a design sprint for a mutual aid network",
    currentlyIntoUpdatedAt: "2026-06-11T14:00:00Z",
    interests: ["Design", "Art", "Sustainability", "Local Events"],
    lookingFor: ["Community", "Collaborators", "Project Partners"],
    availability: "Open to Meet",
    coordinates: { lat: 37.8324, lng: -122.2664 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 155, connector: 120, neighbor: 175, total: 450 },
    badges: [
      { type: "connector", earnedAt: "2026-04-15", label: "Connector", emoji: "🔗" },
      { type: "circle_founder", earnedAt: "2026-03-01", label: "Circle Founder", emoji: "🌱" },
    ],
    streakCount: 30,
    lastActive: "2026-06-12T10:00:00Z",
    showcaseItems: [
      {
        id: "s21",
        title: "Mutual Aid Network Redesign",
        category: "Design",
        coverImage: "https://picsum.photos/seed/mutualaid/600/400",
        description: "Redesigned the volunteer coordination system for Bay Area Mutual Aid — reduced onboarding time by 70%.",
        reactions: { collab: 14, inspired: 52, feedback: 18 },
        createdAt: "2026-04-15T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c2", "c5"],
    eventIds: ["e7", "e11"],
    joinedAt: "2026-02-18T09:00:00Z",
  },
  {
    id: "u21",
    name: "Brandon Osei",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=brandon&backgroundColor=b6e3f4",
    profession: "Founder",
    neighborhood: "SoMa",
    city: "San Francisco",
    bio: "Building a platform for Black creatives to monetize their work. Raised $800k pre-seed. First-gen founder.",
    personalityPrompt: "Building in public because the alternative is building alone.",
    currentlyInto: "Onboarding our first 100 creators",
    currentlyIntoUpdatedAt: "2026-06-12T10:00:00Z",
    interests: ["Startups", "Art", "Music", "AI"],
    lookingFor: ["Mentorship", "Project Partners", "Community"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7762, lng: -122.4016 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 185, connector: 125, neighbor: 95, total: 405 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-05-01", label: "Showcase Star", emoji: "✨" },
      { type: "seven_day_streak", earnedAt: "2026-05-22", label: "7-Day Streak", emoji: "🔥" },
    ],
    streakCount: 20,
    lastActive: "2026-06-12T10:00:00Z",
    showcaseItems: [
      {
        id: "s22",
        title: "Crea — Creator Monetization",
        category: "Software",
        coverImage: "https://picsum.photos/seed/crea/600/400",
        description: "A Substack-meets-Patreon for Black creatives — own your audience, own your revenue.",
        link: "https://crea.so",
        reactions: { collab: 22, inspired: 55, feedback: 20 },
        createdAt: "2026-04-28T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c3"],
    eventIds: ["e1", "e4"],
    joinedAt: "2026-02-22T09:00:00Z",
  },
  {
    id: "u22",
    name: "Mei Lin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=meilin&backgroundColor=d1f0c2",
    profession: "Writer",
    neighborhood: "Richmond",
    city: "San Francisco",
    bio: "Speculative fiction writer and podcast host. My stories are about cities that don't exist yet but probably should.",
    personalityPrompt: "I wrote a story about this exact moment three years ago.",
    currentlyInto: "Writing a novella set in a future Oakland",
    currentlyIntoUpdatedAt: "2026-06-10T19:00:00Z",
    interests: ["Books", "Music", "Art", "Travel"],
    lookingFor: ["Creative Feedback", "Community", "Friends"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7787, lng: -122.4700 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 140, connector: 70, neighbor: 85, total: 295 },
    badges: [
      { type: "showcase_star", earnedAt: "2026-04-30", label: "Showcase Star", emoji: "✨" },
    ],
    streakCount: 10,
    lastActive: "2026-06-11T19:30:00Z",
    showcaseItems: [
      {
        id: "s23",
        title: "Cities That Don't Exist Yet (Podcast)",
        category: "Writing",
        coverImage: "https://picsum.photos/seed/citiespodcast/600/400",
        description: "A speculative fiction podcast exploring alternative urban futures. 40k listeners, featured in NPR.",
        reactions: { collab: 5, inspired: 79, feedback: 12 },
        createdAt: "2026-03-15T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c7", "c9"],
    eventIds: ["e11", "e15"],
    joinedAt: "2026-03-05T09:00:00Z",
  },
  {
    id: "u23",
    name: "Jaylen Brooks",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jaylen&backgroundColor=ffd5dc",
    profession: "Musician",
    neighborhood: "Fruitvale",
    city: "Oakland",
    bio: "R&B artist and music producer. Oakland native. I make music that sounds like summer in the Bay.",
    personalityPrompt: "Every song is a love letter to the city.",
    currentlyInto: "Headlining my first show at Starline Social Club",
    currentlyIntoUpdatedAt: "2026-06-11T12:00:00Z",
    interests: ["Music", "Art", "Local Events", "Food"],
    lookingFor: ["Collaborators", "Community", "Friends"],
    availability: "Attending Events",
    coordinates: { lat: 37.7749, lng: -122.2213 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 160, connector: 100, neighbor: 130, total: 390 },
    badges: [
      { type: "first_event_hosted", earnedAt: "2026-03-20", label: "First Event Hosted", emoji: "🏠" },
    ],
    streakCount: 13,
    lastActive: "2026-06-12T12:00:00Z",
    showcaseItems: [
      {
        id: "s24",
        title: "Bay Summer (EP)",
        category: "Music",
        coverImage: "https://picsum.photos/seed/baysummer/600/400",
        description: "A 6-track R&B EP that captures what summer feels like in East Oakland. Spotify-featured in three editorial playlists.",
        reactions: { collab: 10, inspired: 83, feedback: 7 },
        createdAt: "2026-05-05T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c3", "c8"],
    eventIds: ["e4", "e9"],
    joinedAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "u24",
    name: "Claire Moreau",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=claire&backgroundColor=c0aede",
    profession: "Marketer",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    bio: "Community-led growth strategist. Helped build Notion's ambassador program from 0 to 500k members.",
    personalityPrompt: "Community isn't a channel. It's the whole company.",
    currentlyInto: "Building a community playbook for early-stage startups",
    currentlyIntoUpdatedAt: "2026-06-12T09:30:00Z",
    interests: ["Startups", "Books", "Coffee", "Fashion"],
    lookingFor: ["Coffee Chats", "Mentorship", "Collaborators"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7762, lng: -122.4295 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 135, connector: 145, neighbor: 90, total: 370 },
    badges: [
      { type: "connector", earnedAt: "2026-04-25", label: "Connector", emoji: "🔗" },
    ],
    streakCount: 17,
    lastActive: "2026-06-12T09:30:00Z",
    showcaseItems: [],
    vouches: [],
    circleIds: ["c1", "c7"],
    eventIds: ["e6", "e8"],
    joinedAt: "2026-03-08T09:00:00Z",
  },
  {
    id: "u25",
    name: "Andre Santos",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=andre&backgroundColor=b6e3f4",
    profession: "Photographer",
    neighborhood: "Mission",
    city: "San Francisco",
    bio: "Street photographer and zine maker. Born in Brazil, raised in SF, documenting both.",
    personalityPrompt: "Every corner of the Mission has been photographed. Not by me. Yet.",
    currentlyInto: "Publishing my first zine: SF Through the Rain",
    currentlyIntoUpdatedAt: "2026-06-11T16:00:00Z",
    interests: ["Photography", "Art", "Travel", "Music"],
    lookingFor: ["Creative Feedback", "Collaborators", "Friends"],
    availability: "Open to Meet",
    coordinates: { lat: 37.7583, lng: -122.4158 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 125, connector: 70, neighbor: 100, total: 295 },
    badges: [],
    streakCount: 4,
    lastActive: "2026-06-11T17:00:00Z",
    showcaseItems: [
      {
        id: "s25",
        title: "SF Through the Rain (Zine)",
        category: "Photography",
        coverImage: "https://picsum.photos/seed/sfrain/600/400",
        description: "A 32-page photo zine documenting SF street life during winter rain. Limited print run of 200.",
        reactions: { collab: 3, inspired: 55, feedback: 8 },
        createdAt: "2026-05-20T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c4", "c8"],
    eventIds: ["e2", "e10"],
    joinedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "u26",
    name: "Kezia Atieno",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kezia&backgroundColor=d1f0c2",
    profession: "Student",
    neighborhood: "Piedmont",
    city: "Oakland",
    bio: "Urban planning PhD candidate at UC Berkeley. Studying how cities can intentionally design for serendipitous encounters.",
    personalityPrompt: "I'm writing my dissertation on why people feel lonely in cities. The irony isn't lost on me.",
    currentlyInto: "Field research in Oakland's mixed-use corridors",
    currentlyIntoUpdatedAt: "2026-06-12T11:00:00Z",
    interests: ["Sustainability", "Local Events", "Books", "Hiking"],
    lookingFor: ["Community", "Mentorship", "Project Partners"],
    availability: "Open to Meet",
    coordinates: { lat: 37.8254, lng: -122.2292 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 95, connector: 90, neighbor: 120, total: 305 },
    badges: [
      { type: "early_member", earnedAt: "2026-01-25", label: "Early Member", emoji: "🐣" },
    ],
    streakCount: 22,
    lastActive: "2026-06-12T11:00:00Z",
    showcaseItems: [],
    vouches: [],
    circleIds: ["c7", "c9"],
    eventIds: ["e11", "e13"],
    joinedAt: "2026-01-25T09:00:00Z",
  },
  {
    id: "u27",
    name: "Felix Oduya",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=felix&backgroundColor=ffd5dc",
    profession: "Fitness",
    neighborhood: "Rockridge",
    city: "Oakland",
    bio: "Ultra-marathon runner and coach. I believe that running slowly is a radical act in a city obsessed with speed.",
    personalityPrompt: "I once ran 100 miles. I also once ate a whole pizza. Both have value.",
    currentlyInto: "Training a group for the Bay-to-Breakers 12k",
    currentlyIntoUpdatedAt: "2026-06-11T07:00:00Z",
    interests: ["Fitness", "Hiking", "Local Events", "Sustainability"],
    lookingFor: ["Community", "Friends", "Collaborators"],
    availability: "Open to Meet",
    coordinates: { lat: 37.8454, lng: -122.2470 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 70, connector: 140, neighbor: 180, total: 390 },
    badges: [
      { type: "hundred_day_streak", earnedAt: "2026-05-10", label: "100-Day Streak", emoji: "⭐" },
      { type: "connector", earnedAt: "2026-04-20", label: "Connector", emoji: "🔗" },
    ],
    streakCount: 112,
    lastActive: "2026-06-12T06:00:00Z",
    showcaseItems: [],
    vouches: [],
    circleIds: ["c10"],
    eventIds: ["e13", "e15"],
    joinedAt: "2026-01-05T09:00:00Z",
  },
  {
    id: "u28",
    name: "Naomi Hecht",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=naomi&backgroundColor=c0aede",
    profession: "Artist",
    neighborhood: "Nob Hill",
    city: "San Francisco",
    bio: "Textile artist and weaver. I make large-format woven pieces that you can read like maps.",
    personalityPrompt: "Every loom is a city in miniature.",
    currentlyInto: "Installing a piece at the SF MOMA gift shop",
    currentlyIntoUpdatedAt: "2026-06-10T13:00:00Z",
    interests: ["Art", "Fashion", "Books", "Photography"],
    lookingFor: ["Creative Feedback", "Community", "Collaborators"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7930, lng: -122.4110 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 150, connector: 75, neighbor: 90, total: 315 },
    badges: [],
    streakCount: 3,
    lastActive: "2026-06-10T14:00:00Z",
    showcaseItems: [
      {
        id: "s26",
        title: "City Weaves Collection",
        category: "Art",
        coverImage: "https://picsum.photos/seed/cityweaves/600/400",
        description: "Hand-woven textile maps of Bay Area neighborhoods. Each piece takes 3-6 months to complete.",
        reactions: { collab: 4, inspired: 67, feedback: 11 },
        createdAt: "2026-04-05T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c3", "c8"],
    eventIds: ["e9", "e10"],
    joinedAt: "2026-02-28T09:00:00Z",
  },
  {
    id: "u29",
    name: "Tyler Nguyen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tyler&backgroundColor=b6e3f4",
    profession: "Software Engineer",
    neighborhood: "Dogpatch",
    city: "San Francisco",
    bio: "iOS engineer at Linear. Side project: building an app that helps people remember the names of plants.",
    personalityPrompt: "My app has 12 users and I love all of them personally.",
    currentlyInto: "Learning SwiftUI with zero prior iOS experience",
    currentlyIntoUpdatedAt: "2026-06-11T22:00:00Z",
    interests: ["AI", "Gaming", "Coffee", "Fitness"],
    lookingFor: ["Friends", "Coffee Chats", "Collaborators"],
    availability: "Open to Chat",
    coordinates: { lat: 37.7586, lng: -122.3905 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 130, connector: 60, neighbor: 70, total: 260 },
    badges: [],
    streakCount: 8,
    lastActive: "2026-06-12T00:30:00Z",
    showcaseItems: [
      {
        id: "s27",
        title: "PlantMind iOS App",
        category: "Software",
        coverImage: "https://picsum.photos/seed/plantmind/600/400",
        description: "Point your phone at a plant and it tells you its name, care instructions, and nearest nursery.",
        reactions: { collab: 6, inspired: 22, feedback: 15 },
        createdAt: "2026-05-15T12:00:00Z",
      },
    ],
    vouches: [],
    circleIds: ["c1", "c2"],
    eventIds: ["e5", "e6"],
    joinedAt: "2026-03-20T09:00:00Z",
  },
  {
    id: "u30",
    name: "Rosa Delgado",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rosa&backgroundColor=d1f0c2",
    profession: "Nonprofit",
    neighborhood: "Excelsior",
    city: "San Francisco",
    bio: "Executive director of a youth arts org in the Excelsior. 20 years building community in SF. I'm not leaving.",
    personalityPrompt: "I've been to every neighborhood meeting since 2008. I have opinions.",
    currentlyInto: "Launching a summer mural program for Excelsior youth",
    currentlyIntoUpdatedAt: "2026-06-12T10:00:00Z",
    interests: ["Volunteering", "Art", "Local Events", "Sustainability"],
    lookingFor: ["Community", "Project Partners", "Collaborators"],
    availability: "Attending Events",
    coordinates: { lat: 37.7249, lng: -122.4326 },
    visibilityState: "Visible to Everyone",
    communityScore: { builder: 105, connector: 190, neighbor: 260, total: 555 },
    badges: [
      { type: "community_pillar", earnedAt: "2026-05-25", label: "Community Pillar", emoji: "🌟" },
      { type: "hundred_days", earnedAt: "2026-05-20", label: "100 Days in Cove", emoji: "🏅" },
    ],
    streakCount: 38,
    lastActive: "2026-06-12T10:00:00Z",
    showcaseItems: [
      {
        id: "s28",
        title: "Excelsior Youth Arts Program",
        category: "Nonprofit",
        coverImage: "https://picsum.photos/seed/excelsior/600/400",
        description: "Free arts education for 200+ Excelsior youth. Murals, photography, music, and film. Running since 2010.",
        reactions: { collab: 17, inspired: 88, feedback: 5 },
        createdAt: "2026-04-25T12:00:00Z",
      },
    ],
    vouches: [
      { id: "v30", giverId: "u19", giverName: "Marcus Obi", giverAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcusobi&backgroundColor=ffd5dc", type: "Community Builder", note: "Rosa is the glue of this city.", createdAt: "2026-05-28T10:00:00Z" },
    ],
    circleIds: ["c5", "c6"],
    eventIds: ["e3", "e7"],
    joinedAt: "2026-01-08T09:00:00Z",
  },
];
